# Generated by Django 2.0.13 on 2019-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('texto', 'Texto simples'), ('imagem', 'Imagem'), ('youtube', 'Vídeo do Youtube')], default='texto', max_length=20),
        ),
    ]
