# Generated by Django 2.0.13 on 2019-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='id_video_youtube',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
